spring.datasource.url=jdbc:postgresql://dpg-xxxxx.oregon-postgres.render.com:5432/hanumansangam
spring.datasource.username=admin
spring.datasource.password=QBrmECqxeY8i8h9ng8ZuwrWkBdGpwSFn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
