
spring.datasource.url=jdbc:postgresql://dpg-xxxxx/hanumansangam
spring.datasource.username= admin
spring.datasource.password=QBrmECqxeY8i8h9ng8ZuwrWkBdGpwSFn

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
